#! /bin/bash

# CPSC 351-Summer 2017 Assignment 1
# run-shell
# Purpose: Compile and run the shell.cpp program
# 
# @author Daniel Bravo <bravod@csu.fullerton.edu>
# @author Colbert Chu <colbertchu@csu.fullerton.edu>
# @author Anthony Hernandez <herankoana@csu.fullerton.edu>
# @author Peter Vu <vupeter@csu.fullerton.edu>
# @version 1.0 07/26/17 


# Clear the terminal to make room for time output
clear

# Run the shell program
if [ -f shell.out ]; then
    rm shell.out
fi
g++ shell.cpp -o shell.out && ./shell.out
rm shell.out
