#! /bin/bash

# CPSC 351-Summer 2017 Assignment 1
# run-shell
# Purpose: Compile, run and time a serial and parallel downloader.
# 
# @author Daniel Bravo <bravod@csu.fullerton.edu>
# @author Colbert Chu <colbertchu@csu.fullerton.edu>
# @author Anthony Hernandez <herankoana@csu.fullerton.edu>
# @author Peter Vu <vupeter@csu.fullerton.edu>
# @version 1.0 07/26/17 

# Clear the terminal
clear

# Make a folder for the download files
mkdir test_downloads
mkdir test_downloads/s test_downloads/p

# Run the serial downloader
if [ -f serial.out ]; then
    rm serial.out
fi
echo "Serial Downloader"
g++ serial.cpp -o serial.out && time ./serial.out
rm serial.out

# Add space
echo

# Run the parallel downloader
if [ -f parallel.out ]; then
    rm parallel.out
fi
echo "Parallel Downloader"
g++ parallel.cpp -o parallel.out && time ./parallel.out
rm parallel.out

# Ask user whether to delete files
echo
read -p "Would you like to delete the files? It will delete the directory that was created, 'test_downloads' (y/n) " response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    rm -rfv test_downloads
fi
