#! bash

# Clear the terminal to make room for time output
clear

# Run the serial downloader
if [ -f serial.out ]; then
    rm serial.out
fi
echo "Serial Downloader"
g++ serial.cpp -o serial.out && time ./serial.out
rm serial.out

# Run the parallel downloader
if [ -f parallel.out ]; then
    rm parallel.out
fi
echo "Parallel Downloader"
g++ parallel.cpp -o parallel.out && time ./parallel.out
rm parallel.out